name: Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Build
        env:
          CI: false
        run: |
          npx lerna run build

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish production image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/founder-z/jidoca-2:latest
          push: true
