name: Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          npx lerna run build
